In [1]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,Dropout
import numpy as np

In [2]:
mnist=keras.datasets.mnist

In [3]:
mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [4]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [5]:
# Print the shapes of the arrays
print("Train images shape:", x_train.shape)   # (60000, 28, 28)
print("Train labels shape:", y_train.shape)   # (60000,)
print("Test images shape:", x_test.shape)     # (10000, 28, 28)
print("Test labels shape:", y_test.shape)     # (10000,)

Train images shape: (60000, 28, 28)
Train labels shape: (60000,)
Test images shape: (10000, 28, 28)
Test labels shape: (10000,)


In [6]:
# scale images to the [0,1] range
x_train=x_train.astype("float32")/255
x_test=x_test.astype("float32")/255

In [7]:
#make sure images gave shape(28,28,1)
x_train=np.expand_dims(x_train,-1)
x_test=np.expand_dims(x_test,-1)
print("x_train_shape",x_train.shape)
print("x_test_shape",x_test.shape)

x_train_shape (60000, 28, 28, 1)
x_test_shape (10000, 28, 28, 1)


In [8]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
# covert class vectors to binary class matrices
y_train=keras.utils.to_categorical(y_train,10)
y_test=keras.utils.to_categorical(y_test,10)
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [10]:
y_train.shape

(60000, 10)

In [11]:
x_train.shape

(60000, 28, 28, 1)

In [12]:
mnist_model=Sequential()

In [13]:
mnist_model.add(Conv2D(32,kernel_size=(3,3),activation="relu",input_shape=(28,28,1)))
mnist_model.add(MaxPooling2D(pool_size=(2,2)))
mnist_model.add(Conv2D(64,kernel_size=(3,3),activation="relu"))
mnist_model.add(MaxPooling2D(pool_size=(2,2)))
mnist_model.add(Flatten())
mnist_model.add(Dropout(0.5))
mnist_model.add(Dense(10,activation="softmax"))


In [14]:
mnist_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2  (None, 13, 13, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 5, 5, 64)          0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)              0

In [15]:
mnist_model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
x_train.shape

(60000, 28, 28, 1)

In [17]:
y_train.shape

(60000, 10)

In [18]:
mnist_model.fit(x_train, y_train, batch_size=128, epochs=15, validation_split=0.1)

Epoch 1/15
422/422 [==============================] - 43s 99ms/step - loss: 0.3671 - accuracy: 0.8874 - val_loss: 0.0870 - val_accuracy: 0.9755
Epoch 2/15
422/422 [==============================] - 40s 96ms/step - loss: 0.1125 - accuracy: 0.9653 - val_loss: 0.0570 - val_accuracy: 0.9843
Epoch 3/15
422/422 [==============================] - 39s 92ms/step - loss: 0.0853 - accuracy: 0.9738 - val_loss: 0.0454 - val_accuracy: 0.9875
Epoch 4/15
422/422 [==============================] - 42s 100ms/step - loss: 0.0705 - accuracy: 0.9775 - val_loss: 0.0423 - val_accuracy: 0.9893
Epoch 5/15
422/422 [==============================] - 40s 95ms/step - loss: 0.0640 - accuracy: 0.9802 - val_loss: 0.0400 - val_accuracy: 0.9893
Epoch 6/15
422/422 [==============================] - 40s 94ms/step - loss: 0.0575 - accuracy: 0.9822 - val_loss: 0.0388 - val_accuracy: 0.9895
Epoch 7/15
422/422 [==============================] - 39s 93ms/step - loss: 0.0515 - accuracy: 0.9839 - val_loss: 0.0349 - val_accuracy

In [19]:
score = mnist_model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.02716444991528988
Test accuracy: 0.991100013256073
